---
- block:
  - name: ensure certificates and gnupg is installed
    apt:
      name: [ca-certificates, gnupg, apt-transport-https]
      state: present
  - name: add PGDG repository key
    apt_key: url='{{ postgres_pgdg.key }}'
  - name: add PGDG apt repository 
    apt_repository: repo='{{ postgres_pgdg.repo }}'
  tags: [pgpool_install, install]
  when: not pgpool_install_os

- name: install pgpool
  apt: name=pgpool2 state=latest
  tags: [pgpool_install, install]

- name: configure pgpool
  template: src=pgpool.conf.j2 dest=/etc/pgpool2/pgpool.conf
  notify: restart pgpool

- import_tasks: ssh_connection.yml
  tags: pgpool_ssh

- name: copy failover script
  template: src=failover.sh.j2 dest=/home/postgres/failover.sh mode=+x

- name: ensure pgpool is running
  service: name=pgpool2 state=started
